%YAML:1.0
---
K_front: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 760.88739555990253, 0., 658.03203638352647, 0.,
       761.5460355313345, 376.54339530623002, 0., 0., 1. ]
dist_front: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -0.025872835549213328, 0.03150043650444289,
       0.00021782367383829209, 0.0011617065985499169,
       -0.0088062957836504609 ]
